apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-csi-migration-4
  namespace: demo-csi-migration
spec:
  selector:
    matchLabels:
      app: demo-csi-migration-4
  serviceName: demo-csi-migration-4
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-csi-migration-4
    spec:
      containers:
        - name: demo-csi-migration-4
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: 
        resources:
          requests:
            storage: 1Gi
