apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-csi-migration-2
  namespace: demo-csi-migration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-csi-migration-2
  template:
    metadata:
      labels:
        app: demo-csi-migration-2
    spec:
      containers:
      - name: demo-csi-migration-2-container
        image: nginx
        volumeMounts:
        - name: nginx-persistent-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-persistent-storage
        persistentVolumeClaim:
          claimName: demo-csi-migration-2
