apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-csi-migration-5
  namespace: default
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
