apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-csi-migration-2
  namespace: demo-csi-migration
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
