apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-csi-migration-2
  namespace: demo-csi-migration
spec:
  storageClassName: aws-ebs-gp2
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi